Update Data Schema/Model
wisdom-oss/service-water-rights pull request #5
Opened 2024-01-23 12:09 UTC by dr4hcu5-jan

Since the tool used to get the data about the water rights has been updated and now delivers better data this service needs to be updated to handle the newly available data.
This update entails the following tasks

- [ ] Draft a new database schema and new composite types if needed
- [ ] Change the database driver of the microservice to enhance support for the composite types
- [ ] Implement the composite types in the microservice

Merging this pr closes the following issues: #4

2024-01-25 21:13 UTC, cptpiepmatz requested changes

2024-01-25 21:22 UTC, dr4hcu5-jan commented on resources/queries.sql
> +FROM nlwkn_water_rights.e_usage_locations;
since this part is still wip

2024-01-25 21:23 UTC, dr4hcu5-jan commented on resources/init.sql
> +CREATE TABLE IF NOT EXISTS water_rights.usage_locations
Which type is referenced in this comment, I'm only seeing a table

2024-01-25 21:26 UTC, dr4hcu5-jan commented on resources/init.sql
> +            unit  text
postgres does not allow to mark field not null in a composite type

2024-01-25 22:02 UTC, cptpiepmatz commented on resources/init.sql
> +CREATE TABLE IF NOT EXISTS water_rights.usage_locations
`water_rights.usage_locations` should probably be singular.

2024-01-25 22:08 UTC, dr4hcu5-jan commented on resources/init.sql
> +CREATE TABLE IF NOT EXISTS water_rights.usage_locations
Plural because this is a table containing a `usage_location` in each row and not a extra type

2024-01-26 08:42 UTC, cptpiepmatz commented on resources/init.sql
> +CREATE TABLE IF NOT EXISTS water_rights.usage_locations
I overlooked that, sorry.

2024-01-30 12:01 UTC, dr4hcu5-jan commented
This pr is currently blocked due to missing data in the database until wisdom-oss/nlwkn-rs#2 is resolved

2024-05-29 09:10 UTC, cptpiepmatz approved these changes

2024-05-29 09:17 UTC, cptpiepmatz approved these changes

2024-05-29 09:23 UTC, merged